# Generated by Django 3.2.7 on 2021-11-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MArticles', '0005_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(editable=False, max_length=750, null=True, unique=True),
        ),
    ]
