# Generated by Django 3.2.7 on 2022-03-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MArticles', '0008_auto_20220203_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.ManyToManyField(null=True, to='MArticles.Visitior'),
        ),
    ]
