# Generated by Django 3.2.7 on 2022-03-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MArticles', '0009_auto_20220325_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='views',
            field=models.ManyToManyField(to='MArticles.Visitior'),
        ),
    ]
