# Generated by Django 3.2.7 on 2022-03-25 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MArticles', '0010_alter_article_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitior',
            old_name='ip_address',
            new_name='ipaddress',
        ),
    ]
