# Generated by Django 3.2.7 on 2022-03-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MArticles', '0012_article_total_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='total_views',
            field=models.IntegerField(null=True),
        ),
    ]
