# Generated by Django 3.2.7 on 2022-03-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MArticles', '0014_alter_article_total_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='views',
            field=models.ManyToManyField(blank=True, to='MArticles.Visitior'),
        ),
    ]
