# Generated by Django 3.2.7 on 2022-03-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MArticles', '0015_alter_article_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitior',
            name='total_views',
            field=models.IntegerField(default=0),
        ),
    ]
