# Generated by Django 3.2.7 on 2022-03-25 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MArticles', '0017_alter_visitior_total_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitior',
            name='total_views',
        ),
    ]
