# Generated by Django 3.2.7 on 2021-11-17 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MCourses', '0007_auto_20211117_1354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ('chapter_no',)},
        ),
    ]
