# Generated by Django 3.2.7 on 2022-02-03 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MCourses', '0008_alter_chapter_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='views',
        ),
        migrations.DeleteModel(
            name='IpModel',
        ),
    ]
