# Generated by Django 3.2.7 on 2022-03-26 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EHub', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='name',
        ),
    ]
