# Generated by Django 3.2.7 on 2021-10-31 05:09

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EHub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, unique=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='Frameworks/')),
                ('slug', models.SlugField(editable=False, null=True, unique=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EHub.profile')),
            ],
        ),
        migrations.CreateModel(
            name='IpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Programming Language',
                'verbose_name_plural': 'Programming Languages',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, unique=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('slug', models.SlugField(editable=False, null=True, unique=True)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('difficulty_level', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=50, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EHub.profile')),
                ('chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MSoftwareDevelopment.chapter')),
                ('framework', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MSoftwareDevelopment.framework')),
                ('next_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='MSoftwareDevelopment.topic')),
                ('previous_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous', to='MSoftwareDevelopment.topic')),
                ('views', models.ManyToManyField(blank=True, related_name='post_views', to='MSoftwareDevelopment.IpModel')),
            ],
            options={
                'ordering': ('-published_date',),
            },
        ),
        migrations.CreateModel(
            name='FrameworkComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('commented_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='MSoftwareDevelopment.frameworkcomment')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frameworkcomments', to='MSoftwareDevelopment.topic')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EHub.profile')),
            ],
            options={
                'ordering': ('-commented_on',),
            },
        ),
        migrations.AddField(
            model_name='framework',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MSoftwareDevelopment.programmlanguage', verbose_name='Programming Language'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='framework',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MSoftwareDevelopment.framework'),
        ),
    ]
