# Generated by Django 3.2.7 on 2021-11-17 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MProgrammingLanguage', '0005_auto_20211117_1408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ('chapter_no',)},
        ),
        migrations.AlterModelOptions(
            name='topics',
            options={'ordering': ('topic_no',)},
        ),
    ]
